version: "3"

services:
  db:
    image: mysql:8.2.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
    volumes:
      - db-data:/sites/{DOMAIN_NAME}/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - app-network
    cpus: 0.5
    mem_limit: 1024m

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.2-php8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - wordpress-data:/var/www/html
      - /sites/{DOMAIN_NAME}/nginx:/etc/nginx # so plugins like W3 total cache can see & validate the nginx config
      - type: bind # for adding custom PHP configs
        source: /sites/{DOMAIN_NAME}/php-config.ini
        target: /usr/local/etc/php/conf.d/php-config.ini
    networks:
      - app-network
    cpus: 1
    mem_limit: 1024m

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.25.3-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - wordpress-data:/var/www/html
      - /sites/{DOMAIN_NAME}/nginx:/etc/nginx # for getting the NGINX config for the current instance
      - /sites/{DOMAIN_NAME}/nginx/log:/var/log/nginx # for writing logs
      - /sites/{DOMAIN_NAME}/nginx/run:/var/run/nginx # for writing logs
    networks:
      - app-network
    cpus: 0.25
    mem_limit: 10m

volumes:
  wordpress-data:
  db-data:

networks:
  app-network:
